DROP TABLE IF EXISTS #TEST
CREATE TABLE #TEST (ID INT PRIMARY KEY)
DECLARE @TEST TABLE (ID INT PRIMARY KEY)

BEGIN TRAN

INSERT INTO #TEST (ID) VALUES (1),(2)
INSERT INTO @TEST (ID) VALUES (1),(2)

ROLLBACK

SELECT * FROM @TEST
SELECT * FROM #TEST